---

kind: pipeline
type: kubernetes
name: lint

steps:
- name: lint docker-compose
  image: docker/compose
  commands:
    - docker-compose -f docker/docker-compose.yml config

trigger:
  event:
    - push

...
