---
kind: pipeline
type: kubernetes
name: hocs

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

environment:
  DOCKER_HOST: tcp://docker:2375 # needed by dind-awscli

steps:
  - name: lint docker-compose
    image: docker/compose
    commands:
      - docker-compose -f docker/docker-compose.yml config
    when:
      event:
        - push

  - name: wait_for_docker
    image: docker
    commands:
      - n=0; until docker stats --no-stream; do echo "Waiting for Docker $n"; n=$((n +1)); sleep 1; done
    when:
      event:
        - promote
        - cron

  - name: pull_data_migration
    image: quay.io/ukhomeofficedigital/dind-awscli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: migration_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: migration_aws_secret_access_key
      AWS_DEFAULT_REGION: eu-west-2
    commands:
      - $(aws ecr get-login --no-include-email)
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/hocs/hocs-data
    depends_on:
      - wait_for_docker
    when:
      event:
        - promote
        - cron

  - name: pull_load_elastic
    image: quay.io/ukhomeofficedigital/dind-awscli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: elastic_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: elastic_aws_secret_access_key
      AWS_DEFAULT_REGION: eu-west-2
    commands:
      - $(aws ecr get-login --no-include-email)
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/hocs/hocs-data-elastic
    depends_on:
      - wait_for_docker
    when:
      event:
        - promote
        - cron

  - name: compose_up
    image: docker/compose
    commands:
      - cd docker
      - cp drone-docker-compose.override.yml docker-compose.override.yml
      - docker-compose up -d
      - ./scripts/composeDone.sh
    depends_on:
      - pull_data_migration
      - pull_load_elastic
    when:
      event:
        - promote
        - cron
 
  - name: integration_test
    image: busybox
    commands:
      - wget --spider --timeout=5 http://localhost:8080/health
    depends_on:
      - compose_up
    when:
      event:
        - promote
        - cron

  - name: compose_down
    image: docker/compose
    commands:
      - cd docker
      - docker-compose down -v
    depends_on:
      - integration_test
    when:
      event:
        - promote
        - cron
...
