---
kind: pipeline
type: kubernetes
name: hocs

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

environment:
  DOCKER_HOST: tcp://docker:2375

steps:
- name: lint docker-compose
  image: docker/compose
  commands:
    - docker-compose -f docker/docker-compose.yml config

- name: docker-compose up
  image: docker/compose
  commands:
    - docker-compose -f docker/docker-compose.yml up
  depends_on:
    - lint docker-compose

- name: docker-compose down
  image: docker/compose
  commands:
    - docker-compose -f docker/docker-compose.yml down
  depends_on:
    - docker-compose up

trigger:
  event:
    - push
...
