---
kind: pipeline
type: kubernetes
name: hocs

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

steps:
  - name: pull_data_migration
    image: quay.io/ukhomeofficedigital/dind-awscli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: migration_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: migration_aws_secret_access_key
      AWS_DEFAULT_REGION: eu-west-2
    commands:
      - $(aws ecr get-login --no-include-email)
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/hocs/hocs-data

  - name: pull_load_elastic
    image: quay.io/ukhomeofficedigital/dind-awscli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: elastic_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: elastic_aws_secret_access_key
      AWS_DEFAULT_REGION: eu-west-2
    commands:
      - $(aws ecr get-login --no-include-email)
      - docker pull 340268328991.dkr.ecr.eu-west-2.amazonaws.com/hocs/hocs-data-elastic

  - name: compose_up
    image: docker/compose
    commands:
      - docker-compose -f docker/docker-compose.yml up postgres
    depends_on:
      - pull_data_migration
      - pull_load_elastic

  - name: compose_down
    image: docker/compose
    commands:
      - docker-compose -f docker/docker-compose.yml down
    depends_on:
      - compose_up

environment:
  DOCKER_HOST: tcp://docker:2375 # needed by dind-awscli

trigger:
  event:
    - push
...
