name: deployToPages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./documentation/package-lock.json
      - name: Build
        working-directory: documentation
        run: |
          npm install
          npm run-script build
      - name: Publish
        uses: actions/upload-pages-artifact@v1
        with:
          PATH: documentation/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
        id: deployment
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
