name: deployToPages

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./documentation/package-lock.json
      - name: Build
        working-directory: documentation
        run: |
          npm install
          npm run-script build
      - name: Publish
        uses: actions/upload-pages-artifact
        with:
          PATH: documentation/_site
      - name: Deploy
        uses: actions/deploy-pages
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: documentation/_site
