name: 'Test'
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start infrastructure
        run: docker-compose -f ./docker/docker-compose.yml up -d localstack postgres keycloak

      - name: Wait for infrastructure
        run: docker/ci/wait-for-infrastructure.sh
        shell: bash

      - name: Start services
        run: docker-compose -f ./docker/docker-compose.yml up casework workflow documents converter audit templates search
